name: climate-science-colormapping
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - xarray
  - matplotlib
  - basemap
  - cartopy
  - jupyter
  - pyyaml
  - netcdf4
  - pip
  - pip: 
      - git+https://github.com/lukelbd/proplot.git
